title: Portugol Padrões
description: Este Wiki se dedica a discutir as variações de implementação da linguagem Portugol e tentar um padrão em uma versão canônica.
theme: just-the-docs

url: https://github.com/leonelsanchesdasilva/portugol-padroes

aux_links:
  Github: https://github.com/leonelsanchesdasilva/portugol-padroes
